/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as AdminTagihanRouteImport } from './routes/admin/tagihan'
import { Route as AdminDataUserRouteImport } from './routes/admin/data-user'
import { Route as AdminDataPembayaranRouteImport } from './routes/admin/data-pembayaran'
import { Route as UserHutangRouteImport } from './routes/_user/hutang'
import { Route as UserDataRouteImport } from './routes/_user/data'
import { Route as UserBayarRouteImport } from './routes/_user/bayar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AdminTagihanRoute = AdminTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataUserRoute = AdminDataUserRouteImport.update({
  id: '/data-user',
  path: '/data-user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataPembayaranRoute = AdminDataPembayaranRouteImport.update({
  id: '/data-pembayaran',
  path: '/data-pembayaran',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserHutangRoute = UserHutangRouteImport.update({
  id: '/hutang',
  path: '/hutang',
  getParentRoute: () => UserRoute,
} as any)
const UserDataRoute = UserDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => UserRoute,
} as any)
const UserBayarRoute = UserBayarRouteImport.update({
  id: '/bayar',
  path: '/bayar',
  getParentRoute: () => UserRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof UserIndexRoute
  '/bayar': typeof UserBayarRoute
  '/data': typeof UserDataRoute
  '/hutang': typeof UserHutangRoute
  '/admin/data-pembayaran': typeof AdminDataPembayaranRoute
  '/admin/data-user': typeof AdminDataUserRoute
  '/admin/tagihan': typeof AdminTagihanRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/bayar': typeof UserBayarRoute
  '/data': typeof UserDataRoute
  '/hutang': typeof UserHutangRoute
  '/admin/data-pembayaran': typeof AdminDataPembayaranRoute
  '/admin/data-user': typeof AdminDataUserRoute
  '/admin/tagihan': typeof AdminTagihanRoute
  '/': typeof UserIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/_user/bayar': typeof UserBayarRoute
  '/_user/data': typeof UserDataRoute
  '/_user/hutang': typeof UserHutangRoute
  '/admin/data-pembayaran': typeof AdminDataPembayaranRoute
  '/admin/data-user': typeof AdminDataUserRoute
  '/admin/tagihan': typeof AdminTagihanRoute
  '/_user/': typeof UserIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/bayar'
    | '/data'
    | '/hutang'
    | '/admin/data-pembayaran'
    | '/admin/data-user'
    | '/admin/tagihan'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bayar'
    | '/data'
    | '/hutang'
    | '/admin/data-pembayaran'
    | '/admin/data-user'
    | '/admin/tagihan'
    | '/'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/admin'
    | '/_user'
    | '/_user/bayar'
    | '/_user/data'
    | '/_user/hutang'
    | '/admin/data-pembayaran'
    | '/admin/data-user'
    | '/admin/tagihan'
    | '/_user/'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/tagihan': {
      id: '/admin/tagihan'
      path: '/tagihan'
      fullPath: '/admin/tagihan'
      preLoaderRoute: typeof AdminTagihanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-user': {
      id: '/admin/data-user'
      path: '/data-user'
      fullPath: '/admin/data-user'
      preLoaderRoute: typeof AdminDataUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-pembayaran': {
      id: '/admin/data-pembayaran'
      path: '/data-pembayaran'
      fullPath: '/admin/data-pembayaran'
      preLoaderRoute: typeof AdminDataPembayaranRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/hutang': {
      id: '/_user/hutang'
      path: '/hutang'
      fullPath: '/hutang'
      preLoaderRoute: typeof UserHutangRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/data': {
      id: '/_user/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof UserDataRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/bayar': {
      id: '/_user/bayar'
      path: '/bayar'
      fullPath: '/bayar'
      preLoaderRoute: typeof UserBayarRouteImport
      parentRoute: typeof UserRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDataPembayaranRoute: typeof AdminDataPembayaranRoute
  AdminDataUserRoute: typeof AdminDataUserRoute
  AdminTagihanRoute: typeof AdminTagihanRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDataPembayaranRoute: AdminDataPembayaranRoute,
  AdminDataUserRoute: AdminDataUserRoute,
  AdminTagihanRoute: AdminTagihanRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteChildren {
  UserBayarRoute: typeof UserBayarRoute
  UserDataRoute: typeof UserDataRoute
  UserHutangRoute: typeof UserHutangRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserBayarRoute: UserBayarRoute,
  UserDataRoute: UserDataRoute,
  UserHutangRoute: UserHutangRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
